name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [g84_fts]
    name: "🚧 Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools -y
          mkdir -p toolchain
          cd toolchain
          echo 'Download antman and sync'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S=05012024
          echo 'Done'

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 60

      # === خطوات نسخ KernelSU وتنفيذ الباتشات قبل البناء ===
      - name: Checkout KernelSU-Next
        uses: actions/checkout@v4
        with:
          repository: KernelSU-Next/KernelSU-Next
          ref: 0d6bdc6364cbfc73517dcfdf7ab23b0ba8045553
          path: KernelSU-Next  # سينزل هنا

      - name: Copy patches and files
        run: |
          cp KernelSU/10_enable_susfs_for_ksu.patch KernelSU-Next/10_enable_susfs_for_ksu.patch
          cp KernelSU/kernel/sucompat.h KernelSU-Next/kernel/sucompat.h
          cd KernelSU-Next
          git apply 10_enable_susfs_for_ksu.patch
          cd ..
          git apply 50_add_susfs_in_kernel-5.4.patch


      - name: Run build
        run: |
          DEVICE=${{matrix.device}} KSU=1 ./build.sh

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: O_kernel-${{matrix.device}}
          path: AnyKernel3/O*.zip
